server:
  host: 127.0.0.1
  port: 8080
journey:
  insertion:
    worker-pool-size: 20
    bulk-insert-size: 1000
  import:
    max-upload-file-size: 1000000
  parser:
    worker-pool-size: 10
database:
  mongo:
    username: "root"
    password: "changeit"
    hostname: "127.0.0.1"
    port: "27017"
    name: "csvLoader"
    options: "?maxPoolSize=100"