// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// JourneyUsecase is an autogenerated mock type for the JourneyUsecase type
type JourneyUsecase struct {
	mock.Mock
}

// ImportFromCSVFile provides a mock function with given fields: reader
func (_m *JourneyUsecase) ImportFromCSVFile(reader io.Reader) {
	_m.Called(reader)
}

type mockConstructorTestingTNewJourneyUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewJourneyUsecase creates a new instance of JourneyUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewJourneyUsecase(t mockConstructorTestingTNewJourneyUsecase) *JourneyUsecase {
	mock := &JourneyUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
