# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go - Test with coverage

on:
  pull_request:
    banches:
      - main
      - "release/**"
  push:
    branches:
      - "release/**"
      - main


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 10

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'

    - run: go version
      
    - uses: gwatts/go-coverage-action@v1
      id: coverage
      with:
        # Optional coverage threshold
        # use fail-coverage to determine what should happen below this threshold
        coverage-threshold: 90

        # collect coverage for all packages beyond the one under test
        cover-pkg: ./...

        # Ignore code-generated files when calculating coverage totals
        ignore-pattern: |
          ^me\/coutcout\/covoiturage\/mocks

    - name: Build
      run: go build -v ./...

    - name: Test
      uses: robherley/go-test-action@v0.1.0

    - name: Golang mutation testing
      uses: rescDev/go-mutesting-action@v1.0.0
      